@startuml
:Manager: as admin
:Cleaner: as cleaner

admin --> (Manage rooms)
(Update room info) .up.> (Manage rooms) : extends
(List all rooms) .up.> (Manage rooms) : extends

admin --> (Manage facilities)
(List facilities) .up.> (Manage facilities) : extends
(Update facility) .up.> (Manage facilities) : extends
(Delete facility) .up.> (Manage facilities) : extends
(Add facility) .up.> (Manage facilities) : extends
(Reserve facility for a room) .up.> (Manage facilities) : extends

admin --> (Manage bookings)
(Book a room) .up.> (Manage bookings) : extends
(Update booking) .up.> (Manage bookings) : extends
(Delete booking) .up.> (Manage bookings) : extends
(List bookings) .up.> (Manage bookings) : extends


admin --> (Manage cleaning)
(Request cleaning) .up.> (Manage cleaning) : extends
(Update request) .up.> (Manage cleaning) : extends
(Cancel request) .up.> (Manage cleaning) : extends
cleaner --> (List cleaning to do)
cleaner --> (Confirm cleaning done)
cleaner --> (Generate cleaning report)
(Generate cleaning report) .up.> (Manage cleaning) : extends
@enduml